var DB2 = {
    "spirits" :
        [{
            "nr": "10001",
            "artikelid": "25053",
            "varnummer": "100",
            "namn": "Braastad XO",
            "namn2": "",
            "prisinklmoms": "442.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2000-08-07",
            "slutlev": " ",
            "varugrupp": "Cognac",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Cognac, Fine Champagne",
            "ursprunglandnamn": "Frankrike",
            "producent": "Tiffon",
            "leverantor": "Arcus Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1001",
            "artikelid": "190719",
            "varnummer": "10",
            "namn": "Vanlig Vodka",
            "namn2": "",
            "prisinklmoms": "195.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Svensk Export Vodka AB",
            "leverantor": "Fondberg",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1001201",
            "artikelid": "51029",
            "varnummer": "10012",
            "namn": "Dworek Vodka",
            "namn2": "",
            "prisinklmoms": "190.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2004-12-06",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Polen",
            "producent": "Tarpan Fabryka Likierow",
            "leverantor": "TIWA Trading AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1001202",
            "artikelid": "407506",
            "varnummer": "10012",
            "namn": "Dworek Vodka",
            "namn2": "",
            "prisinklmoms": "100.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2009-10-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Polen",
            "producent": "Tarpan Fabryka Likierow",
            "leverantor": "TIWA Trading AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1003802",
            "artikelid": "513291",
            "varnummer": "10038",
            "namn": "Esping Jul B\u00c3\u00a4sk",
            "namn2": "",
            "prisinklmoms": "195.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2010-11-15",
            "slutlev": " ",
            "varugrupp": "Kryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Symposion International",
            "leverantor": "Symposion International AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "32%",
            "modul": "",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1004703",
            "artikelid": "723841",
            "varnummer": "10047",
            "namn": "Nils Oscar",
            "namn2": "Celebration Ale",
            "prisinklmoms": "43.70",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-02-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Nils Oscar Company",
            "leverantor": "The Nils Oscar Company AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "9.4%",
            "modul": "T5",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1004801",
            "artikelid": "733051",
            "varnummer": "10048",
            "namn": "Rhum J. M",
            "namn2": "",
            "prisinklmoms": "729.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Rom, M\u00c3\u00b6rk",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Martinique",
            "ursprunglandnamn": "Frankrike",
            "producent": "Les Heritiers Crassous de Mede",
            "leverantor": "Cask Sweden AB",
            "argang": "2001",
            "provadargang": "",
            "alkoholhalt": "46.6%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1004901",
            "artikelid": "733068",
            "varnummer": "10049",
            "namn": "Rhum J.M",
            "namn2": "",
            "prisinklmoms": "1399.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-04-02",
            "slutlev": " ",
            "varugrupp": "Rom, M\u00c3\u00b6rk",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Martinique",
            "ursprunglandnamn": "Frankrike",
            "producent": "Les Heritiers Crassous de Mede",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "44.8%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1005001",
            "artikelid": "733084",
            "varnummer": "10050",
            "namn": "Balcones Texas",
            "namn2": "",
            "prisinklmoms": "899.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Whisky, Malt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Balcones Distilling",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "52.2%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9242002",
            "artikelid": "871925",
            "varnummer": "92420",
            "namn": "Borgogno",
            "namn2": "Barolo Chinato Giacomo Borgogno",
            "prisinklmoms": "325.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, S\u00c3\u00b6tt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Piemonte, Barolo",
            "ursprunglandnamn": "Italien",
            "producent": "Giacomo Borgogno",
            "leverantor": "The WineAgency Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "16%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9242201",
            "artikelid": "871933",
            "varnummer": "92422",
            "namn": "Leitz",
            "namn2": "R\u00c3\u00bcdesheimer Berg Kaisersteinfels Terrassen",
            "prisinklmoms": "299.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Rheingau",
            "ursprunglandnamn": "Tyskland",
            "producent": "Weingut Leitz",
            "leverantor": "Johan Lidby Vinhandel AB",
            "argang": "2013",
            "provadargang": "",
            "alkoholhalt": "12%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9243201",
            "artikelid": "872226",
            "varnummer": "92432",
            "namn": "Langhe Nebbiolo",
            "namn2": "Azienda Agricola Cascina Nuova Elio Altare",
            "prisinklmoms": "159.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Stramt & Nyanserat",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Piemonte, Langhe",
            "ursprunglandnamn": "Italien",
            "producent": "Azienda Agricola Cascina Nuova",
            "leverantor": "Carovin AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9243401",
            "artikelid": "872003",
            "varnummer": "92434",
            "namn": "Fleurie Chapelle des Bois",
            "namn2": "Domaine Jules Desjourneys",
            "prisinklmoms": "365.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, Beaujolais, Beaujolais Cru, F",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Jules Desjourneys",
            "leverantor": "The WineAgency Sweden AB",
            "argang": "2010",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9243501",
            "artikelid": "872009",
            "varnummer": "92435",
            "namn": "Ch\u00c3\u00a2teau des Annereaux",
            "namn2": "Lalande de Pomerol",
            "prisinklmoms": "159.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Stramt & Nyanserat",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bordeaux, Lalande de Pomerol",
            "ursprunglandnamn": "Frankrike",
            "producent": "Ch\u00c3\u00a2teau des Annereaux",
            "leverantor": "Winebee AB",
            "argang": "2010",
            "provadargang": "2010",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "1",
            "koscher": "0"
        }, {
            "nr": "9243701",
            "artikelid": "872163",
            "varnummer": "92437",
            "namn": "Moulin \u00c3\u00a0 Vent Les Michelons",
            "namn2": "Domaine Jules Desjourneys",
            "prisinklmoms": "469.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, Beaujolais, Beaujolais Cru, M",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Jules Desjourneys",
            "leverantor": "The WineAgency Sweden AB",
            "argang": "2010",
            "provadargang": "",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9243801",
            "artikelid": "872183",
            "varnummer": "92438",
            "namn": "Fleurie Les Moriers",
            "namn2": "Domaine Jules Desjourneys",
            "prisinklmoms": "349.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, Beaujolais, Beaujolais Cru, F",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Jules Desjourneys",
            "leverantor": "The WineAgency Sweden AB",
            "argang": "2010",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9244101",
            "artikelid": "872215",
            "varnummer": "92441",
            "namn": "Crozes Hermitage",
            "namn2": "Alain Graillot",
            "prisinklmoms": "196.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Kryddigt & Mustigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Rhonedalen, C\u00c3\u00b4tes du Rh\u00c3\u00b4ne, Crozes-Her",
            "ursprunglandnamn": "Frankrike",
            "producent": "Alain Graillot",
            "leverantor": "Ward Wines AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9244501",
            "artikelid": "872233",
            "varnummer": "92445",
            "namn": "Tel\u00c3\u00a9maco",
            "namn2": "Azienda Agricola Campogrande Altare - Bonanni",
            "prisinklmoms": "359.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Fylligt & Smakrikt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Ligurien, Liguria di Levante",
            "ursprunglandnamn": "Italien",
            "producent": "Azienda Agricola Campogrande A",
            "leverantor": "Carovin AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9244901",
            "artikelid": "872350",
            "varnummer": "92449",
            "namn": "Villa Maria",
            "namn2": "Single Vineyard Taylor's Pass Chardonnay",
            "prisinklmoms": "179.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Fylligt & Smakrikt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Marlborough",
            "ursprunglandnamn": "Nya Zeeland",
            "producent": "Villa Maria Estate",
            "leverantor": "Fondberg",
            "argang": "2007",
            "provadargang": "2007",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9245001",
            "artikelid": "872353",
            "varnummer": "92450",
            "namn": "Riesling Federspiel",
            "namn2": "Weingut Emmerich Knoll",
            "prisinklmoms": "199.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Nieder\u00c3\u00b6sterreich, Wachau",
            "ursprunglandnamn": "\u00c3\u2013sterrike",
            "producent": "Weingut Emmerich Knoll",
            "leverantor": "Gullberg by Stockwine AB",
            "argang": "2013",
            "provadargang": "",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9245101",
            "artikelid": "872356",
            "varnummer": "92451",
            "namn": "Langhe Arneis Bricco Cappellina",
            "namn2": "Gianni Voerzio",
            "prisinklmoms": "129.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Piemonte, Langhe",
            "ursprunglandnamn": "Italien",
            "producent": "Gianni Voerzio",
            "leverantor": "Granqvist Beverage House AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9245401",
            "artikelid": "872359",
            "varnummer": "92454",
            "namn": "Loibenberg Smaragd Riesling Reid",
            "namn2": "Weingut Emmerich Knoll",
            "prisinklmoms": "319.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Nieder\u00c3\u00b6sterreich, Wachau",
            "ursprunglandnamn": "\u00c3\u2013sterrike",
            "producent": "Knoll",
            "leverantor": "Gullberg by Stockwine AB",
            "argang": "2013",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9245501",
            "artikelid": "872379",
            "varnummer": "92455",
            "namn": "Ried Pfaffenberg",
            "namn2": "Riesling Kabinett Weingut Emmerich Knoll",
            "prisinklmoms": "279.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Nieder\u00c3\u00b6sterreich, Wachau",
            "ursprunglandnamn": "\u00c3\u2013sterrike",
            "producent": "Weingut Emmerich Knoll",
            "leverantor": "Gullberg by Stockwine AB",
            "argang": "2013",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9245601",
            "artikelid": "872382",
            "varnummer": "92456",
            "namn": "Gr\u00c3\u00bcner Veltliner Vinothekf\u00c3\u00bcllung Smaragd",
            "namn2": "Weingut Emmerich Knoll",
            "prisinklmoms": "489.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Nieder\u00c3\u00b6sterreich, Wachau",
            "ursprunglandnamn": "\u00c3\u2013sterrike",
            "producent": "Weingut Emmerich Knoll",
            "leverantor": "Gullberg by Stockwine AB",
            "argang": "2013",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9245901",
            "artikelid": "872466",
            "varnummer": "92459",
            "namn": "Sp\u00c3\u00a4tburgunder Herrenwingert",
            "namn2": "Friedrich Becker",
            "prisinklmoms": "399.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Pfalz",
            "ursprunglandnamn": "Tyskland",
            "producent": "Friedrich Becker",
            "leverantor": "Fondberg",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9247501",
            "artikelid": "872559",
            "varnummer": "92475",
            "namn": "Chevalier Montrachet",
            "namn2": "Domaine Leflaive",
            "prisinklmoms": "2959.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-09",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Beaune, Puligny-Mont",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Leflaive",
            "leverantor": "Ward Wines AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9248001",
            "artikelid": "872623",
            "varnummer": "92480",
            "namn": "Puligny-Montrachet Clavoillon",
            "namn2": "Domaine Leflaive",
            "prisinklmoms": "625.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-09",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Beaune, Puligny-Mont",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Leflaive",
            "leverantor": "Ward Wines AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9248101",
            "artikelid": "872633",
            "varnummer": "92481",
            "namn": "Gevrey-Chambertin Lavaux Saint Jacques",
            "namn2": "Domaine Armand Rousseau",
            "prisinklmoms": "1216.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-09",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Nuits, Gevrey-Chambe",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Armand Rousseau",
            "leverantor": "Ward Wines AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9248201",
            "artikelid": "872667",
            "varnummer": "92482",
            "namn": "Charmes-Chambertin",
            "namn2": "Domaine Armand Rousseau",
            "prisinklmoms": "1393.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-09",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Nuits, Gevrey-Chambe",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Armand Rousseau",
            "leverantor": "Ward Wines AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9248301",
            "artikelid": "872670",
            "varnummer": "92483",
            "namn": "Domaine Bott-Geyl",
            "namn2": "Pinot Gris Les Elements",
            "prisinklmoms": "179.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Druvigt & Blommigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Bott-Geyl",
            "leverantor": "Divine AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "1",
            "koscher": "0"
        }, {
            "nr": "9248401",
            "artikelid": "872722",
            "varnummer": "92484",
            "namn": "Mazy-Chambertin",
            "namn2": "Domaine Armand Rousseau",
            "prisinklmoms": "1586.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-09",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Nuits, Gevrey-Chambe",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Armand Rousseau",
            "leverantor": "Ward Wines AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9248701",
            "artikelid": "872777",
            "varnummer": "92487",
            "namn": "Gevrey-Chambertin Clos St Jacques",
            "namn2": "Domaine Armand Rousseau",
            "prisinklmoms": "2416.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-09",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Nuits, Gevrey-Chambe",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Armand Rousseau",
            "leverantor": "Ward Wines AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9250301",
            "artikelid": "873278",
            "varnummer": "92503",
            "namn": "Schubert",
            "namn2": "Pinot Noir",
            "prisinklmoms": "179.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Kryddigt & Mustigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Wellington, Wairarapa",
            "ursprunglandnamn": "Nya Zeeland",
            "producent": "Schubert Wines",
            "leverantor": "AB Wicked Wine Sweden",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "14%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9250401",
            "artikelid": "873295",
            "varnummer": "92504",
            "namn": "Marion's Vineyard Pinot Noir",
            "namn2": "Schubert wines",
            "prisinklmoms": "249.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Kryddigt & Mustigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Wellington, Wairarapa",
            "ursprunglandnamn": "Nya Zeeland",
            "producent": "Schubert Wines",
            "leverantor": "AB Wicked Wine Sweden",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "14%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9253201",
            "artikelid": "874758",
            "varnummer": "92532",
            "namn": "Dom\u00c3\u00a4ne Wachau",
            "namn2": "Gr\u00c3\u00bcner Veltliner Smaragd Achleiten",
            "prisinklmoms": "179.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Nieder\u00c3\u00b6sterreich, Wachau",
            "ursprunglandnamn": "\u00c3\u2013sterrike",
            "producent": "Dom\u00c3\u00a4ne Wachau",
            "leverantor": "Mondo Wine Sweden AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "14%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9253601",
            "artikelid": "875037",
            "varnummer": "92536",
            "namn": "Dom\u00c3\u00a4ne Wachau",
            "namn2": "Riesling Smaragd Achleiten",
            "prisinklmoms": "179.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Nieder\u00c3\u00b6sterreich, Wachau",
            "ursprunglandnamn": "\u00c3\u2013sterrike",
            "producent": "Dom\u00c3\u00a4ne Wachau",
            "leverantor": "Mondo Wine Sweden AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9399702",
            "artikelid": "870650",
            "varnummer": "93997",
            "namn": "Palo Cortado Antique",
            "namn2": "Rey Fernando de Castilla",
            "prisinklmoms": "339.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "Sherry, Torr",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Jerez",
            "ursprunglandnamn": "Spanien",
            "producent": "Bodegas Rey Fernando de Castil",
            "leverantor": "Fondberg",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "20%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9504601",
            "artikelid": "736727",
            "varnummer": "95046",
            "namn": "Clos Ste Hune Riesling",
            "namn2": "Trimbach",
            "prisinklmoms": "1069.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-04-11",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Trimbach",
            "leverantor": "Ward Wines AB",
            "argang": "2007",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9504701",
            "artikelid": "615245",
            "varnummer": "95047",
            "namn": "Masi Riserva Costasera",
            "namn2": "Amarone della Valpolicella Classico",
            "prisinklmoms": "449.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-02-01",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Kryddigt & Mustigt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Venetien, Valpolicella, Amarone della Va",
            "ursprunglandnamn": "Italien",
            "producent": "Masi",
            "leverantor": "Philipson S\u00c3\u00b6derberg AB",
            "argang": "2006",
            "provadargang": "2006",
            "alkoholhalt": "15.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9511901",
            "artikelid": "859520",
            "varnummer": "95119",
            "namn": "Ch\u00c3\u00a2teau Ducluzeau",
            "namn2": "",
            "prisinklmoms": "179.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Fruktigt & Smakrikt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bordeaux, Haut-M\u00c3\u00a9doc, Listrac-M\u00c3\u00a9doc",
            "ursprunglandnamn": "Frankrike",
            "producent": "Cordier Meztrezat",
            "leverantor": "Nigab",
            "argang": "2010",
            "provadargang": "2010",
            "alkoholhalt": "14%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9523409",
            "artikelid": "864082",
            "varnummer": "95234",
            "namn": "Mulderbosch Trippel Chenin Blanc",
            "namn2": "Mulderbosch Vineyards",
            "prisinklmoms": "590.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "3 fl \u00c3\u00a0 750 ml",
            "forslutning": "Naturkork",
            "ursprung": "Western Cape, Coastal Region, Stellenbos",
            "ursprunglandnamn": "Sydafrika",
            "producent": "Mulderbosch Vineyards",
            "leverantor": "Vinunic AB",
            "argang": "2013",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9635701",
            "artikelid": "849470",
            "varnummer": "96357",
            "namn": "Paracombe",
            "namn2": "Shiraz Viognier",
            "prisinklmoms": "219.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-08-01",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Fruktigt & Smakrikt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "South Australia, Adelaide Hills",
            "ursprunglandnamn": "Australien",
            "producent": "Paracombe Premium Wines",
            "leverantor": "Johan Lidby Vinhandel AB",
            "argang": "2010",
            "provadargang": "2010",
            "alkoholhalt": "16%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9801901",
            "artikelid": "863103",
            "varnummer": "98019",
            "namn": "Masi",
            "namn2": "Osar",
            "prisinklmoms": "349.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Venetien, Rosso del Veronese",
            "ursprunglandnamn": "Italien",
            "producent": "Masi",
            "leverantor": "Philipson S\u00c3\u00b6derberg AB",
            "argang": "2007",
            "provadargang": "",
            "alkoholhalt": "14%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9857601",
            "artikelid": "349181",
            "varnummer": "98576",
            "namn": "Diamond Creek",
            "namn2": "Volcanic Hill",
            "prisinklmoms": "1479.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2008-09-15",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Kalifornien, North Coast, Napa Valley",
            "ursprunglandnamn": "USA",
            "producent": "Diamond Creek Vineyards",
            "leverantor": "Svahn Cru Handelsbolag",
            "argang": "2005",
            "provadargang": "",
            "alkoholhalt": "14.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9900001",
            "artikelid": "858030",
            "varnummer": "99000",
            "namn": "W\u00c3\u00bcrzburger Stein Riesling trocken",
            "namn2": "Juliusspital",
            "prisinklmoms": "169.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Druvigt & Blommigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Franken",
            "ursprunglandnamn": "Tyskland",
            "producent": "Juliusspital",
            "leverantor": "Enjoy Wine & Spirits AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9901001",
            "artikelid": "861104",
            "varnummer": "99010",
            "namn": "San Calisto",
            "namn2": "Valle Reale",
            "prisinklmoms": "199.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Fruktigt & Smakrikt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Abruzzerna, Montepulciano d'Abruzzo",
            "ursprunglandnamn": "Italien",
            "producent": "Valle Reale",
            "leverantor": "The WineAgency Sweden AB",
            "argang": "2010",
            "provadargang": "2010",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9901302",
            "artikelid": "861210",
            "varnummer": "99013",
            "namn": "Ch\u00c3\u00a2teau Langoa Barton",
            "namn2": "",
            "prisinklmoms": "286.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bordeaux, Haut-M\u00c3\u00a9doc, Saint-Julien",
            "ursprunglandnamn": "Frankrike",
            "producent": "",
            "leverantor": "Swedish Wine Cellar AB",
            "argang": "2006",
            "provadargang": "",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9904801",
            "artikelid": "859048",
            "varnummer": "99048",
            "namn": "Artemis Cabernet Sauvignon",
            "namn2": "Stag's Leap Wine Cellars",
            "prisinklmoms": "379.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Kalifornien, North Coast, Napa Valley",
            "ursprunglandnamn": "USA",
            "producent": "Stag's Leap Wine Cellars",
            "leverantor": "Vinunic AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9905601",
            "artikelid": "858060",
            "varnummer": "99056",
            "namn": "W\u00c3\u00bcrzburger Stein Silvaner trocken",
            "namn2": "Juliusspital",
            "prisinklmoms": "169.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Franken",
            "ursprunglandnamn": "Tyskland",
            "producent": "Juliusspital",
            "leverantor": "Enjoy Wine & Spirits AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9906101",
            "artikelid": "859066",
            "varnummer": "99061",
            "namn": "De Wetshof Bateleur Chardonnay",
            "namn2": "De Wetshof Estate",
            "prisinklmoms": "249.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Fylligt & Smakrikt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Western Cape, Breede River Valley, Rober",
            "ursprunglandnamn": "Sydafrika",
            "producent": "De Wetshof Estate",
            "leverantor": "Miguel Torres",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9906301",
            "artikelid": "784042",
            "varnummer": "99063",
            "namn": "PSI",
            "namn2": "",
            "prisinklmoms": "279.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Ribera del Duero",
            "ursprunglandnamn": "Spanien",
            "producent": "Bodegas y Vi\u00c3\u00b1edos Alnardo",
            "leverantor": "Arvid Nordquist Vin och Sprith",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "15%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9909202",
            "artikelid": "861233",
            "varnummer": "99092",
            "namn": "Ch\u00c3\u00a2teau L\u00c3\u00a9oville Barton",
            "namn2": "",
            "prisinklmoms": "359.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bordeaux, Haut-M\u00c3\u00a9doc, Saint-Julien",
            "ursprunglandnamn": "Frankrike",
            "producent": "",
            "leverantor": "Swedish Wine Cellar AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9913901",
            "artikelid": "853832",
            "varnummer": "99139",
            "namn": "Barolo Colonnello",
            "namn2": "Poderi Aldo Conterno",
            "prisinklmoms": "749.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Piemonte, Barolo",
            "ursprunglandnamn": "Italien",
            "producent": "Poderi Aldo Conterno",
            "leverantor": "Vinovativa AB",
            "argang": "2009",
            "provadargang": "",
            "alkoholhalt": "15%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9925601",
            "artikelid": "860732",
            "varnummer": "99256",
            "namn": "Vouvray Le Peu Morier",
            "namn2": "Domaine Vincent Car\u00c3\u00aame",
            "prisinklmoms": "179.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-08-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Loiredalen, Touraine, Vouvray",
            "ursprunglandnamn": "Frankrike",
            "producent": "Vincent Car\u00c3\u00aame",
            "leverantor": "Enjoy Wine & Spirits AB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "1",
            "koscher": "0"
        }, {
            "nr": "9929201",
            "artikelid": "860955",
            "varnummer": "99292",
            "namn": "Les Perri\u00c3\u00a8res",
            "namn2": "Domaine Breton",
            "prisinklmoms": "249.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Fruktigt & Smakrikt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Loiredalen, Touraine, Bourgueil",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Breton",
            "leverantor": "Enjoy Wine & Spirits AB",
            "argang": "2010",
            "provadargang": "2010",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "1",
            "koscher": "0"
        }, {
            "nr": "9931801",
            "artikelid": "866140",
            "varnummer": "99318",
            "namn": "Ch\u00c3\u00a2teauneuf-du-Pape",
            "namn2": "Chante le Merle Vieilles Vignes",
            "prisinklmoms": "411.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Rhonedalen, C\u00c3\u00b4tes du Rh\u00c3\u00b4ne, Ch\u00c3\u00a2teaune",
            "ursprunglandnamn": "Frankrike",
            "producent": "Bosquet des Papes",
            "leverantor": "Johan Lidby Vinhandel AB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "15.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9934001",
            "artikelid": "868545",
            "varnummer": "99340",
            "namn": "Glenburgie 1994",
            "namn2": "Sherry",
            "prisinklmoms": "1099.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Whisky, Malt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Skottland, Highlands, Speyside",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Gordon & MacPhail",
            "leverantor": "Symposion International AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "46%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9935701",
            "artikelid": "866159",
            "varnummer": "99357",
            "namn": "Bosquet des Papes",
            "namn2": "A la Gloire de Mon Grand-P\u00c3\u00a8re",
            "prisinklmoms": "375.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Kryddigt & Mustigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Rhonedalen, C\u00c3\u00b4tes du Rh\u00c3\u00b4ne, Ch\u00c3\u00a2teaune",
            "ursprunglandnamn": "Frankrike",
            "producent": "Bosquet des Papes",
            "leverantor": "Johan Lidby Vinhandel AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "15.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9939101",
            "artikelid": "866198",
            "varnummer": "99391",
            "namn": "Chateauneuf-du-Pape",
            "namn2": "Cuv\u00c3\u00a9e Reserv\u00c3\u00a9e Domaine du Pegau",
            "prisinklmoms": "425.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Kryddigt & Mustigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Rhonedalen, C\u00c3\u00b4tes du Rh\u00c3\u00b4ne, Ch\u00c3\u00a2teaune",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine du Pegau",
            "leverantor": "Origo Wine Import",
            "argang": "2011",
            "provadargang": "2011",
            "alkoholhalt": "14.7%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9939201",
            "artikelid": "866416",
            "varnummer": "99392",
            "namn": "Barolo Brunate",
            "namn2": "Ceretto",
            "prisinklmoms": "499.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Piemonte, Barolo",
            "ursprunglandnamn": "Italien",
            "producent": "Ceretto",
            "leverantor": "Carovin AB",
            "argang": "2005",
            "provadargang": "",
            "alkoholhalt": "14.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9939301",
            "artikelid": "866537",
            "varnummer": "99393",
            "namn": "Heimbourg",
            "namn2": "Gewurztraminer Domaine Zind Humbrecht",
            "prisinklmoms": "239.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Druvigt & Blommigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Zind Humbrecht",
            "leverantor": "Vinunic AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9939401",
            "artikelid": "867447",
            "varnummer": "99394",
            "namn": "Domaine Casenobe",
            "namn2": "Rivesaltes",
            "prisinklmoms": "639.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013vrigt starkvin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Languedoc-Roussillon, Rivesaltes",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Casenobe",
            "leverantor": "Provinum Vinhandel AB",
            "argang": "1974",
            "provadargang": "",
            "alkoholhalt": "16%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9939501",
            "artikelid": "867587",
            "varnummer": "99395",
            "namn": "Brunello di Montalcino",
            "namn2": "Il Greppo",
            "prisinklmoms": "749.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-09",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Toscana, Brunello di Montalcino",
            "ursprunglandnamn": "Italien",
            "producent": "Biondi-Santi",
            "leverantor": "The Wine Team",
            "argang": "2009",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9942602",
            "artikelid": "863064",
            "varnummer": "99426",
            "namn": "Masi Angelorum",
            "namn2": "Recioto Classico",
            "prisinklmoms": "149.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, S\u00c3\u00b6tt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Venetien, Valpolicella, Recioto della Va",
            "ursprunglandnamn": "Italien",
            "producent": "Masi",
            "leverantor": "Philipson S\u00c3\u00b6derberg AB",
            "argang": "2009",
            "provadargang": "2009",
            "alkoholhalt": "14%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9944501",
            "artikelid": "866185",
            "varnummer": "99445",
            "namn": "Blanc des Mill\u00c3\u00a9naires",
            "namn2": "Charles Heidsieck",
            "prisinklmoms": "1399.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Mousserande vin, Vitt torrt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Champagne",
            "ursprunglandnamn": "Frankrike",
            "producent": "Charles Heidsieck",
            "leverantor": "Provinum Vinhandel AB",
            "argang": "1995",
            "provadargang": "1995",
            "alkoholhalt": "12%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9945601",
            "artikelid": "866214",
            "varnummer": "99456",
            "namn": "Clos Vougeot Grand Cru",
            "namn2": "Louis Jadot",
            "prisinklmoms": "1095.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Nuits, Vougeot, Clos",
            "ursprunglandnamn": "Frankrike",
            "producent": "Louis Jadot",
            "leverantor": "Vinunic AB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9946701",
            "artikelid": "867424",
            "varnummer": "99467",
            "namn": "Clos Windsbuhl",
            "namn2": "Pinot Gris Domaine Zind Humbrecht",
            "prisinklmoms": "239.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Druvigt & Blommigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Domaine Zind Humbrecht",
            "leverantor": "Vinunic AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9947401",
            "artikelid": "866393",
            "varnummer": "99474",
            "namn": "Echezeaux Grand Cru",
            "namn2": "Louis Jadot",
            "prisinklmoms": "1299.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Nuits, Flagey-\u00c3\u2030ch\u00c3\u00a9",
            "ursprunglandnamn": "Frankrike",
            "producent": "Louis Jadot",
            "leverantor": "Vinunic AB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9947506",
            "artikelid": "866399",
            "varnummer": "99475",
            "namn": "Beaune  Premier Cru Boucherottes",
            "namn2": "Louis Jadot",
            "prisinklmoms": "695.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Magnum",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Beaune, Beaune, Beau",
            "ursprunglandnamn": "Frankrike",
            "producent": "Louis Jadot",
            "leverantor": "Vinunic AB",
            "argang": "2010",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9947601",
            "artikelid": "866581",
            "varnummer": "99476",
            "namn": "Corton Charlemagne Grand Cru",
            "namn2": "Louis Jadot",
            "prisinklmoms": "1039.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bourgogne, C\u00c3\u00b4te de Beaune, Aloxe-Corton",
            "ursprunglandnamn": "Frankrike",
            "producent": "Louis Jadot",
            "leverantor": "Vinunic AB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9949901",
            "artikelid": "868496",
            "varnummer": "99499",
            "namn": "Forster Pechstein",
            "namn2": "Riesling Trocken Reichsrat von Buhl",
            "prisinklmoms": "299.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-19",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Pfalz",
            "ursprunglandnamn": "Tyskland",
            "producent": "Reichsrat von Buhl",
            "leverantor": "janake wine group AB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9954302",
            "artikelid": "866169",
            "varnummer": "99543",
            "namn": "Maglehem 4:15",
            "namn2": "",
            "prisinklmoms": "129.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-10-03",
            "slutlev": " ",
            "varugrupp": "Fruktvin, S\u00c3\u00b6tt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Maglehems musteri",
            "leverantor": "Maglehems Musteri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "15%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "1",
            "koscher": "0"
        }, {
            "nr": "99652008",
            "artikelid": "764070",
            "varnummer": "996520",
            "namn": "Blossa Vingl\u00c3\u00b6gg",
            "namn2": "",
            "prisinklmoms": "153.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-11-01",
            "slutlev": " ",
            "varugrupp": "Gl\u00c3\u00b6gg och Gl\u00c3\u00bchwein",
            "forpackning": "Box",
            "forslutning": "Tappkran",
            "ursprung": "",
            "ursprunglandnamn": "Internationellt m\u00c3\u00a4rke",
            "producent": "Altia",
            "leverantor": "Altia Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "10%",
            "modul": "",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "99701202",
            "artikelid": "762382",
            "varnummer": "997012",
            "namn": "Tegn\u00c3\u00a9r & Son",
            "namn2": "Tradition Ekologisk Vingl\u00c3\u00b6gg",
            "prisinklmoms": "46.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-11-01",
            "slutlev": " ",
            "varugrupp": "Gl\u00c3\u00b6gg och Gl\u00c3\u00bchwein",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Galatea Spirits AB",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "12%",
            "modul": "",
            "sortiment": "TSS",
            "ekologisk": "1",
            "koscher": "0"
        }]