var DB1 = {
    "sprits" :
        [{
            "nr": "10001",
            "artikelid": "25053",
            "varnummer": "100",
            "namn": "Braastad XO",
            "namn2": "",
            "prisinklmoms": "442.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2000-08-07",
            "slutlev": " ",
            "varugrupp": "Cognac",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Cognac, Fine Champagne",
            "ursprunglandnamn": "Frankrike",
            "producent": "Tiffon",
            "leverantor": "Arcus Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1001",
            "artikelid": "190719",
            "varnummer": "10",
            "namn": "Vanlig Vodka",
            "namn2": "",
            "prisinklmoms": "195.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Svensk Export Vodka AB",
            "leverantor": "Fondberg",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }]
}